@startuml
actor User
participant Frontend
participant UserService
participant OAuth2Server
participant NotificationService

User -> Frontend: OAuth2 Authentication()
Frontend -> UserService: OAuth2 Auth Request
UserService -> OAuth2Server: Authenticate User
OAuth2Server -> UserService: Token
UserService -> NotificationService: Send Authentication Event(user_id)
NotificationService -> UserService: Success
UserService -> Frontend: Auth Success with Token
Frontend -> User: Auth Success with Token
@enduml
