version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      DATABASE_URL: DATABASE_URL=postgres://myuser:mypassword@localhost:5432/mydatabase
    ports:
      - "5432:5432"
